apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ng-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rokku-cz/ng-argo-test.git
    targetRevision: HEAD
    path: test
  destination:
    server: https://kubernetes.default.svc
